name: Deploy-EC2

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Rsync deployments
              uses: burnett01/rsync-deployments@6.0.0
              with:
                  switches: --avzr --delete
                  path: ./*
                  remote_path: /home/ubuntu/guidancegrid-backend
                  remote_host: ${{ secrets.AWS_EC2_HOST }}
                  remote_user: ubuntu
                  remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
